from odoo import models, fields, api, _

class BugReportLine(models.Model):
    _name = 'bug.report.line'
    _description = 'Bug Report Line'
    _order = 'configurable_unit_id, version_id'
    _rec_name = 'bug_id'

    bug_id = fields.Many2one('alm.bug', string='Bug', required=True, readonly=True, ondelete='cascade')
    version_id = fields.Many2one('alm.configurable.unit.version', string='Version', required=True, readonly=True, ondelete='cascade')
    configurable_unit_id = fields.Many2one(
        'alm.configurable.unit',
        string='Configurable Unit',
        related='version_id.unit_id',
        store=True,
        readonly=True,
    )
    report_type = fields.Selection([
        ('registered', 'Registered'),
        ('fixed', 'Fixed'),
    ], string='Type', required=True, readonly=True)

    create_uid = fields.Many2one('res.users', string='Report Generated By', readonly=True)
